USE [MarketApi]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].PRODUCT(
	[ID] [int] NOT NULL,
	[NAME] [varchar](16) NOT NULL,
	[DESCRIPTION] [varchar](255) NULL,
	[TYPE] [varchar](50) NULL,
	[PRICE] [NUMERIC](19,2) NULL,
	[CREATEDDATE] [datetime] NULL,
	[ITEMSINSTOCK] [int] NULL
PRIMARY KEY (
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
